#!/bin/bash
function vars {
echo "TARGET"
}
function check {
echo "TARGET=$TARGET"
}
function start {
cd $TARGET
#!/bin/sh
#
# Install Debian Wheezy on Kirkwood devices

# Copyright (c) 2012 Jeff Doozan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


# Version 1.1    [1/24/2013] Revised by Daniel Richard G.
# Version 1.0    [7/14/2012] Initial Release


# Definitions

# Download locations
MIRROR="http://download.doozan.com"

DEB_MIRROR="http://cdn.debian.net/debian"

MKE2FS_URL="$MIRROR/debian/mke2fs"
PKGDETAILS_URL="$MIRROR/debian/pkgdetails"
URL_UBOOT="http://projects.doozan.com/uboot/install_uboot_mtd0.sh"
DEBOOTSTRAP_VERSION=$(wget -q "$DEB_MIRROR/pool/main/d/debootstrap/?C=M;O=D" -O- | grep -o 'debootstrap[^"]*all.deb' | head -n1)
URL_DEBOOTSTRAP="$DEB_MIRROR/pool/main/d/debootstrap/$DEBOOTSTRAP_VERSION"

# Default binary locations
MKE2FS=/sbin/mke2fs
PKGDETAILS=/usr/share/debootstrap/pkgdetails

# Where should the temporary 'debian root' be mounted
#ROOT=/tmp/debian

# debootstrap configuration
RELEASE=jessie
VARIANT=minbase
ARCH=armel

# if you want to install additional packages, add them to the end of this list
EXTRA_PACKAGES=kmod,udev,netbase,ifupdown,iproute,dhcpcd5,iputils-ping,wget,net-tools,ntpdate,dialog
#EXCLUDE_PACKAGES=man,tzdata


##########
##########
#
# Run debootstrap
#
##########
##########

echo ""
echo ""
echo "# Starting debootstrap installation"

/usr/sbin/debootstrap --verbose --no-check-gpg --arch=$ARCH --variant=$VARIANT --include=$EXTRA_PACKAGES  $RELEASE $TARGET $DEB_MIRROR
#/usr/sbin/debootstrap --verbose --no-check-gpg --arch=$ARCH --variant=$VARIANT --exclude=$EXCLUDE_PACKAGES $RELEASE $TARGET $DEB_MIRROR

if [ "$?" -ne "0" ]; then
  echo "debootstrap failed."
  echo "See $TARGET/debootstrap/debootstrap.log for more information."
  exit 1
fi


echo "deb http://security.debian.org $RELEASE/updates main" >> $TARGET/etc/apt/sources.list

cat <<END > $TARGET/etc/apt/apt.conf.d/50doozan
// Conserve disk/flash space by not installing extra packages.
APT::Install-Recommends "0";
APT::Install-Suggests "0";
END

echo debian > $TARGET/etc/hostname
echo LANG=C > $TARGET/etc/default/locale

cat <<END > $TARGET/etc/fw_env.config
# Configuration file for fw_(printenv/saveenv) utility.
# Up to two entries are valid; in this case the redundant
# environment sector is assumed present.
# Note that "Number of sectors" is ignored on NOR.

# MTD device name	Device offset	Env. size	Flash sector size	Number of sectors
/dev/mtd0		0xc0000		0x20000		0x20000
END

cat <<END >> $TARGET/etc/network/interfaces

auto eth0
iface eth0 inet dhcp
END

cat <<END > $TARGET/etc/fstab
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/root       /               ext2    noatime,errors=remount-ro 0 1
$SWAP_DEV       none            swap    sw              0       0
END

# allow login on the serial port, and disable standard console terminals
echo 'T0:2345:respawn:/sbin/getty -L ttyS0 115200 linux' >> $TARGET/etc/inittab
sed -i 's/^\([1-6]:.* tty[1-6]\)/#\1/' $TARGET/etc/inittab

# device does not have a hardware clock
sed -i 's/^#*\(HWCLOCKACCESS\)=.*$/\1=no/' $TARGET/etc/default/hwclock

# use a tmpfs for /tmp
sed -i 's/^#*\(RAMTMP\)=.*$/\1=yes/' $TARGET/etc/default/tmpfs

if [ -e $TARGET/etc/blkid.tab ]; then
  rm $TARGET/etc/blkid.tab
fi
ln -s /dev/null $TARGET/etc/blkid.tab

if [ -e $TARGET/etc/mtab ]; then
  rm $TARGET/etc/mtab
fi
ln -s /proc/mounts $TARGET/etc/mtab

# root password is 'root'
sed -i 's,^root:.*$,root:$1$XPo5vyFS$iJPfS62vFNO09QUIUknpm.:14360:0:99999:7:::,' $TARGET/etc/shadow




cd $TARGET
mount -t proc proc proc/
mount -t sysfs sys sys/
mount -o bind /dev dev/
cp /etc/resolv.conf etc/resolv.conf

chroot $TARGET /usr/bin/apt-get clean


exit 0
}




case "$1" in
  "vars")
    vars
    ;;
  "check")
    check
    ;;
  "start")
    start
    ;;
  *)
    echo "Usage: `basename $0` (vars | check | start)"
    exit 1
    ;;
esac
