#!/bin/bash
function vars {
echo "TARGET"
echo "BOOT"
echo "ROOT"
}
function check {
echo "TARGET=$TARGET"
echo "BOOT=$BOOT"
echo "ROOT=$ROOT"
}
function start {
cd $TARGET
cat > $TARGET/etc/fstab << EOF
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
$ROOT / f2fs rw,noatime 0 0
$BOOT /boot ext2 rw,noatime 0 0
tmpfs          /tmp            tmpfs   defaults          0       0
EOF
exit 0
}

case "$1" in
  "vars")
    vars
    ;;
  "check")
    check
    ;;
  "start")
    start
    ;;
  *)
    echo "Usage: `basename $0` (vars | check | start)"
    exit 1
    ;;
esac
