#!/bin/bash
function vars {
echo "TARGET"
echo "HOSTNAME"
}
function check {
echo "TARGET=$TARGET"
echo "HOSTNAME=$HOSTNAME"
}
function start {
cd $TARGET
mkdir $TARGET/storage
cat >> $TARGET/etc/fstab << EOF
nas:/storage/ /storage/ nfs rw,rsize=32768,wsize=32768,noatime,soft 0 0
nas:/storage/innestech.net/chalky/$HOSTNAME/var/lib/lxc/ /var/lib/lxc/ nfs rw,rsize=32768,wsize=32768,noatime,soft 0 0
EOF


exit 0
}


case "$1" in
  "vars")
    vars
    ;;
  "check")
    check
    ;;
  "start")
    start
    ;;
  *)
    echo "Usage: `basename $0` (vars | check | start)"
    exit 1
    ;;
esac
