#!/bin/bash
function vars {
echo "TARGET"
}
function check {
echo "TARGET=$TARGET"
}
function start {
cd $TARGET

cat > $TARGET/etc/network/interfaces << EOF
auto br0
iface br0 inet dhcp
    bridge_ports eth0
    bridge_fd 0
    bridge_maxwait 0
EOF


cat >> $TARGET/etc/fstab << EOF
cgroup  /sys/fs/cgroup  cgroup  defaults  0   0
EOF


exit 0
}


case "$1" in
  "vars")
    vars
    ;;
  "check")
    check
    ;;
  "start")
    start
    ;;
  *)
    echo "Usage: `basename $0` (vars | check | start)"
    exit 1
    ;;
esac
