#!/bin/bash
function vars {
echo "TARGET"
}
function check {
echo "TARGET=$TARGET"
}
function start {
#reduce
#92420
du -h $TARGET
cd $TARGET
rm $TARGET/boot/*dpkg-bak
du -h $TARGET
exit 0
}








case "$1" in
  "vars")
    vars
    ;;
  "check")
    check
    ;;
  "start")
    start
    ;;
  *)
    echo "Usage: `basename $0` (vars | check | start)"
    exit 1
    ;;
esac
